### ISSUE TITLE
`consult--source-project-*` slow when current buffer is remote

### ISSUE THREAD

**Issue by astoff** [minad/consult#332] opened 2021-06-09 11:49 UTC
Sometimes `consult-buffer` takes about 1 second to pop up when I call it; as far as I can tell, this happens whenever I have at least one remote buffer open via Tramp. Removing `consult--source-project-buffer` and `consult--source-project-file` from the list of sources seems to solve the problem.

Let me know if there is some extra info that can help you.

**Comment by astoff** [comment] 2021-06-09 12:06
Actually, the slowness happens only if the _current_ buffer is remote when I call `consult-buffer`.

**Comment by minad** [comment] 2021-06-09 14:10
What exactly is slow?

**Comment by astoff** [comment] 2021-06-09 14:27
At the moment I call `consult-buffer`, Emacs becomes unresponsive for about 1 second. After that, the candidates appear and everything works normally.

**Comment by minad** [comment] 2021-06-09 14:41
I need a profile of consult-buffer to determine where the slowness comes from. Is the project root function the problem? Or the filtering of the files?

**Comment by astoff** [comment] 2021-06-09 19:47
My `consult-project-root-function` was the pretty standard `(lambda () (when-let ((p (project-current))) (project-root p)))`. I've added an extra `(unless (file-remote-p default-directory) ...)` around it and this seems to solve the problem.

Do you think this is what the project root function should look like, or rather its caller should check first for remote files? My impression is that the caller is in a better position to decide whether or not a certain delay is acceptable.

**Comment by minad** [comment] 2021-06-09 20:07
No, I don't think the caller has a responsibility here. The problem is the slow project root function. Projects could also be remote so I guess this should be fixed upstream?

**Comment by astoff** [comment] 2021-06-10 06:54
Hmm... Since projects can be remote, it follows that project operations can be slow. But I would still expect `project-find-regexp` to always be correct (which it is), even if possibly slow. On the other hand, I would expect `consult-buffer` to always be snappy, even if some features are disabled for remote files.

Personally I'm happy with my modified `consult-project-root-function` that always returns nil on remote files, but I think this is not the ideal behavior as far as `consult-grep` is concerned.

**Comment by minad** [comment] 2021-06-10 08:34
What about writing a better `consult-project-root-function` which caches the result for remote buffers (or maybe even for all buffers)? This should be easy to implement and should fix the problem reliably without downsides.

**Comment by minad** [comment] 2021-06-10 14:36
I close this. We should document this in the wiki, but I don't think anything in Consult itself should be changed. Please let me know if you find out a satisfying solution with caching.

**Closed by minad** 2021-06-10 14:36 UTC

**Comment by astoff** [comment] 2021-06-10 15:03
FWIW, this issue is not just a wiki thing; it affects Consult with the recommended settings, copied and pasted straight from the README.

Maybe `vc-root-dir` is a better suggestion for `consult-project-root-function`. It seems to just gives up on remote files.
