### ISSUE TITLE
consult--grep doesn't set the default directory correctly

### ISSUE THREAD

**Issue by sdevlin** [minad/consult#136] opened 2021-01-05 22:14 UTC
`consult--grep` has some code that looks like this:

    (pcase-let ((`(,prompt . ,default-directory) (consult--directory-prompt prompt dir))) ...)

The apparent intent is to bind `default-directory` as the root directory for the search.

Unfortunately, `pcase-let` doesn't let you bind special variables using that syntax. If you macroexpand the above form a couple times, you get something like this:

    (let*
        ((val
          (consult--directory-prompt prompt dir))
         (x2947
          (car val))
         (x2948
          (cdr val)))
       ...)

You can see that the intended `default-directory` binding is lost in the macroexpansion. This means the grep-like functions always use the current value of `default-directory` as the search root (instead of the project root or whatever).

**Comment by minad** [comment] 2021-01-05 22:16
Are you using Emacs 28?

**Comment by sdevlin** [comment] 2021-01-05 22:33
Yes.

**Comment by minad** [comment] 2021-01-05 22:37
This is a duplicate of #108

**Closed by minad** 2021-01-05 22:37 UTC
