### ISSUE TITLE
Eshell completion with `consult-completion-in-region` unexpected behaviors

### ISSUE THREAD

**Issue by svaante** [minad/consult#461] opened 2021-11-07 01:09 UTC
First off, great package 👍 

I have a feeling this is due to eshell completion quirks and not consult. So feel free to close this if this is the case, or if anybody has any suggestion on how to make this work.

The expected behavior is how the \*Completions\* buffer is populated and what text is inserted when the completion is expanded.

`emacs -Q`

```emacs-lisp
(package-initialize)
(require 'consult)
(require 'vertico)
(vertico-mode)

;; substring doesn't work with the completions described below
(setq completion-styles '(basic)) 

(setq completion-in-region-function
      (lambda (&rest args)
        (apply (if vertico-mode
                   #'consult-completion-in-region
                 #'completion--in-region)
               args)))
```
## First example

M-x eshell
```sh
$ mkdir somefolder
$ cd somefolder
$ touch somefile
$ chmod +x ./somefile
$ ./some<Tab>
```
Outcome:
![Screenshot 2021-11-07 at 01 53 34](https://user-images.githubusercontent.com/1129021/140628302-fb722591-83e1-4401-9ddb-d3bb784c451a.png)

Expected result would be `$ ./some<Tab> -> ./somefile`

## Second example
M-x eshell
```sh
$ mkdir somefolder
$ cd somefolder
$ touch 1 2 3
$ ls <Tab>
```
Outcome:
![Screenshot 2021-11-07 at 01 43 45](https://user-images.githubusercontent.com/1129021/140628105-d04bdeea-2df0-4821-9ee3-9da306c04aa2.png)

Expected result would be that the completion list is populated with 1 2 3

**Comment by minad** [comment] 2021-11-07 03:32
I just tried to reproduce this and it works as expected on Emacs 27.1. I don't see your results but the result you described as expected. Is your Consult version up to date? Closing this for now. Please let me know how it goes on your end.

**Comment by svaante** [comment] 2021-11-07 14:17
Thanks for looking into it. I am still able to reproduce the issue on ﻿﻿12ec003. I am using emacs 28.0.50.

Did some digging around for the second issue.
https://github.com/minad/consult/blob/3b18b04524f0e963070ab6c61d4d3a3f10507d12/consult.el#L2343
At this point `initial` is `""` which is then passed as `dir` which might be undefined behavior. If we pass `nil` `read-file-name-default` will use `default-directory` which then leads to the expected behavior. I can't seem to find the commit responsible on the 28 branch. Which changes the behavior of `read-file-name-default` or if that is the case at all.

**Comment by oantolin** [comment] 2021-11-07 15:17
I tried both scenarios here and for the first one, `./some <TAB>` I get no completions! If instead I go `some <TAB>`, then it completes to `somefile`. For the second one scenario, I get exactly the behavior @svaante observed: `somefolder` is the sole completion candidate, and I have to actually add a slash to see the contents of `somefolder`.

**Comment by minad** [comment] 2021-11-07 15:25
@oantolin Thanks, I will check this again. Maybe I did something wrong when I tried to reproduce this (27.1, emacs -Q, vertico). I am not using `consult-completion-in-region` regularly because of Corfu, so this command does not get the same testing and coverage in my regular use.

**Comment by oantolin** [comment] 2021-11-07 16:05
It could be changes in Emacs 28. I have 28 on both my machines: a fairly "old" 28 on my Chromebook and a relatively recent one on my Windows laptop (recent enough to have native compilation).

**Comment by oantolin** [comment] 2021-11-07 16:08
Huh, there's even a slight difference between my two Emacs 28s! The results I gave above were on the Windows laptop. I just tried on my Chromebook and almost the same thing happened, except that for the `somefile` executable, here `som <TAB>` does not complete to `somefile` (for `./some <TAB>` I also get no completion, like on Windows).

**Comment by oantolin** [comment] 2021-11-07 16:38
The first, scenario, completing the path of an executable seems to be something eshell's completion table does. I don't think it can be fixed in `consult-completion-in-region`, the candidate just isn't present in the collection handed to `consult-completion-in-region`.

The second scenario does seem to be due to the call to `read-file-name` that @svaante pointed out. Instead of relying on the undefined behavior (which seems to have changed?) we can start the file name completion in the default-directory and use a minibuffer setup hook to insert the initial text. I'll make a PR with that small change. It seems like a good idea: be explicit in 3 lines of code rather than have a 5 lines comment explaining some trickery that relies on undefined behavior.

**Comment by oantolin** [comment] 2021-11-07 16:43
Note that there is what seems like a reasonable alternative: start the completion in the directory `(file-name-directory initial)`, and only insert `(file-name-nondirectory initial)` into the minibuffer. That would fail for some completion styles, like partial-completion, which can handle partially typed paths, like `/u/s/d/w` for `/usr/share/dict/words` (it would fail because `(file-name-directory initial)` would be the non-existent `/u/s/d` "directory").

**Comment by minad** [comment] 2021-11-07 16:46
Thanks Omar for looking into this! Is the solution you've chosen now better than the "reasonable alternative"?

**Comment by oantolin** [comment] 2021-11-07 16:52
> Is the solution you've chosen now better than the "reasonable alternative"?

Yes, the "reasonable alternative" works fine for initial texts that either have no path or have a fully specified path up to the last bit which can be partial (so it would work for `/usr/share/dict/wo`, for example). But inserting the whole initial text works in those cases plus also working for the more powerful partially written path handling of completion styles like partial-completion or initials. I think the PR is the way to go and it more directly expresses our intention: run file completion, with the given initial text!

**Comment by minad** [comment] 2021-11-07 17:12
Thanks for the fix! @svaante please confirm that it works for you!

**Closed by minad** 2021-11-07 17:12 UTC
Labels: unconfirmed

**Comment by oantolin** [comment] 2021-11-07 17:14
To be clear: that commit should fix the second thing, and the first thing seems like it needs to be fixed at the eshell level.

**Comment by minad** [comment] 2021-11-07 17:19
Okay, maybe report this as a regression upstream?

**Comment by svaante** [comment] 2021-11-07 17:22
> To be clear: that commit should fix the second thing, and the first thing seems like it needs to be fixed at the eshell level.

Works on my end! Thanks @oantolin @minad 🥇
