### ISSUE TITLE
UI issue with long lines in results

### ISSUE THREAD

**Issue by dangirsh** [minad/consult#361] opened 2021-07-14 11:51 UTC
Thanks for this outstanding package!

I'm using a config very similar to [this one](https://dev.arcology.garden/cce/selectrum.html), and noticed that `consult-ripgrep` has a broken UI. The issue was that I could move my selection off of the bottom of the results, without the view updating. I can include a gif of this happening, if this description isn't clear.

After some searching, I found that reducing the `max-columns` parameter to `ripgrep` fixed this issue for me. A quick fix may be to reduce this default from 1000 chars to ~200.

generated    Jul 14, 2021 13:50:46
system       Ubuntu 20.10 Linux 5.8.0-44-generic x86_64 x
emacs        28.0.50 feature/native-comp fa65c044f ~/.emacs.d/ -> ~/.emacs.d/
features     CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ IMAGEMAGICK JPEG JSON LCMS2 LIBSELINUX LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM LUCID ZLIB

**Comment by minad** [comment] 2021-07-14 12:00
The description is unfortunately not sufficiently clear. I assume this is a duplicate of #246, which is Selectrum-specific (see https://github.com/raxod502/selectrum/issues/491). Display issues are usually not Consult issues, but should rather be fixed in Selectrum or in whichever UI you are using. As a cross-check you can try my [Vertico](https://github.com/minad/vertico) package, which can be used a Selectrum drop-in. What confuses me here is that you say that the issue is fixed if one adjusts the max-columns parameter. In any case, make sure that all packages are updated to the newest commit.

**Closed** 2021-07-15 13:35 UTC
