### ISSUE TITLE
consult with vertico: yank-pop not doing what I expect

### ISSUE THREAD

**Issue by floli** [minad/consult#553] opened 2022-04-17 15:38 UTC
Hello,
I doubt that this is going to be a bug report, rather some request for help. ;-)

When using consult, together with vertico:

```
emacs -Q

(package-initialize)
(require 'vertico)
(require 'consult)
(vertico-mode)
```

and add `something` to the kill ring (`M-w` / `C-w`) and call `consult-yank-pop`

* The default selection is empty, i.e., when I press Enter, nothing is yanked, just the command is finished
* The first selection is always an empty string, selecting it has the same result as the default.
* The string that was just killed is at position 2.

The functionality I desire is rather that the last kill is pre-selected and can be yanked with just `M-y RET`.

Can you give me a way to achieve that and maybe explain the rationale of the actual behavior to me?

Thanks!

**Comment by minad** [comment] 2022-04-17 16:04
> The functionality I desire is rather that the last kill is pre-selected and can be yanked with just M-y RET.

That's odd. This is exactly the behavior that you should observe. I just confirmed this again with emacs -Q on Emacs 27 and 28. Is something else wrong with your installation (Emacs 29, pgtk, some other odd issues, ...)?

**Comment by minad** [comment] 2022-04-17 16:08
Also maybe take a look at the value of the `kill-ring` variable and try the command `consult-yank-from-kill-ring`? Note that Emacs 28 and newer comes with `yank-pop` and `yank-from-kill-ring` itself, which behaves like the Consult function minus the in-buffer preview. Do these commands work for you?

**Comment by minad** [comment] 2022-04-17 16:18
I have another suspicion. `consult--read-from-kill-ring` tries to take the current string from the clipboard (interprogram paste in Emacs terminology. See this code:

https://github.com/minad/consult/blob/a924b3b0d943d12c71d23964da7733251f4705b2/consult.el#L3539-L3540

It could be that your interprogram paste functionality is broken which could be caused by your GUI setup or operating system. Maybe the way Consult tries to obtain the interprogram paste is wrong. I will check this.

**Comment by minad** [comment] 2022-04-17 16:27
I suspect that you have the empty string in your X11 clipboard. Have you tried turning your computer off and on again? ;)

**Comment by floli** [comment] 2022-04-17 17:58
It really seems to be X11 related, I was unable to reproduce it on a non-X terminal.

The X11 clipboard contains an actual string, confirmed by inserting it using the middle-mouse into the Emacs buffer. Still, both `yank-pop` and `consult-yank-pop` behave identical as described in my original post.

* GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-09
* KDE / X11

but as far as I remember I have the same behavior using awesome-wm and also with Emacs versions before 28.1. I am unable to really confirm either at the moment.

**Comment by minad** [comment] 2022-04-17 18:45
Okay. I suggest you delete this line

https://github.com/minad/consult/blob/a924b3b0d943d12c71d23964da7733251f4705b2/consult.el#L3540

from `consult--read-from-kill-ring` (and also from `read-from-kill-ring`) and evaluate the defun with `C-M-x`. If the problem goes away then we know that it has to do with a broken interprogram paste. If not we can dig deeper and investigate if something else is at fault. 

But given that you also observe the issue with `yank-pop` this is likely not a Consult issue only and should then be addressed by Emacs itself and reported via `report-emacs-bug`. Therefore I close the issue here. Please let me know if removing `(current-kill 0)` solves it or if you need further help with reporting an upstream issue.

**Closed by minad** 2022-04-17 18:45 UTC
Labels: unconfirmed

**Comment by floli** [comment] 2022-04-17 19:27
Thanks for your assistance! 

I removed the `current-kill 0)` at both occurrences and `eval-defun` both. However, the behavior has not changed.

Fun fact is that the inclusion of the line was triggered by a bug report by me: https://github.com/minad/consult/issues/443

**Comment by minad** [comment] 2022-04-17 19:33
Okay I see. This is odd then. I don't know what causes this. Did you inspect the `kill-ring` variable before and after yank-pop? I think there is no other way than debugging `read-from-kill-ring` and `consult--read-from-kill-ring` step by step.

**Comment by mattiasdrp** [comment] 2022-09-07 09:14
I have the same kind of problem. I'm used to have the `kill-ring` cycle when using `yank-pop` and can't get this behaviour with `consult-yank-pop`

When using `yank-pop` the value of `kill-ring-yank-pointer` changes. Example, I just killed 1, 2 and 3.

`kill-ring`:

```elisp
(#("3" 0 1
   (fontified t))
 #("2" 0 1
   (fontified t))
 #("1" 0 1
   (fontified t)))
```

`kill-ring-yank-pointer`

```elisp
(#("3" 0 1
   (fontified t))
 #("2" 0 1
   (fontified t))
 #("1" 0 1
   (fontified t)))
```

If I `yank-pop` 3 times it will yank `1` and the value of `kill-ring-yank-pointer` changes:

```elisp
(#("1" 0 1 (fontified t)))
```

When starting from the same initial setup (1, 2 and 3 have been killed) with consult, I can hit `consult-yank-pop` once and select from its menu to chose the value I want to yank. After selecting `1`, the value of `kill-ring-yank-pointer` hasn't changed and if I use `consult-yank-pop` after that the default value will be `3` and not `1`.

It looks like this cycling can be opted in or out:

```elisp
(defcustom yank-from-kill-ring-rotate t
  "Whether using `yank-from-kill-ring' should rotate `kill-ring-yank-pointer'.
If non-nil, the kill ring is rotated after selecting previously killed text."
  :type 'boolean
  :group 'killing
  :version "28.1")
```

But this doesn't seem to be used in consult

**Comment by minad** [comment] 2022-09-07 09:39
@matthiasdrp Feel free to open a PR which improves this behavior. We could even rotate the kill ring in the completion interface, such that the kills are sorted with the kill ring pointer taken into account.

**Comment by mattiasdrp** [comment] 2022-09-07 17:39
I'll try to do it this week-end then :-)
