### ISSUE TITLE
Feature request: arbitrarily transform heading strings in consult-outline

### ISSUE THREAD

**Issue by Hugo-Heagren** [minad/consult#480] opened 2021-12-16 10:42 UTC
I use consult-heading for navigating latex documents. This is great, but the `\section`, `\begin` etc. markup shows up in the list of headings, when really what I want is a list of heading titles. I would like to tidy up the heading strings before they are presented. Could there be a buffer local variable pointing at a function for transforming heading titles before they are used as candidates (if nil, don't do anything. It could be set in a mode-hook)? Or alternatively an alist linking modes with transformation functions, which is checked and the relevant function applied by `consult-outline`. 

I would be happy to implement this if you like the idea.

**Comment by minad** [comment] 2021-12-16 11:18
> Or alternatively an alist linking modes with transformation functions, which is checked and the relevant function applied by consult-outline.

Mhm. I think I like the idea. But there are a few implications.

* `consult-outline` currently creates full line candidates. The `consult-location` completion category is used for that reason. It results in an `occur-mode` buffer if we do `embark-export`. We would lose that if we transform the lines, or at least the occur-mode buffer cannot be edited anymore (I am not sure what is going to happen actually, will occur editing refuse to edit?). On the other hand it is a questionable feature to edit the outline in an occur-mode buffer. But there is an easy way out - we only have to change the value of the `consult-location` text property. Currently the value stores the line number and the marker. We could change it to line number, marker and original line in order to restore the occur-mode export. So this should not be a blocker.

* We also have `consult-imenu`. Does this already do what you need? Probably the problem is that you don't want the flattening of the imenu for a readable outine. By adding these transformers we are moving imenu and outline closer together which is maybe not desired. I like to have focused commands with clear boundaries. But we could alternatively consider to extend `consult-imenu` with a non-flattened mode, where only the leaves of the imenu nodes are the actual candidate strings instead of the path. By doing that we would avoid adding transformers, since the imenu backend already creates the imenu in the desired form.

* Are there more useful transformers? Would it only apply to latex? I usually have an arbitrary limit of three to justify the introduction of an alist configuration variable.

* Furthermore one would have to agree upon transformations which would be universally accepted. Of course the user can reconfigure, but we need reasonable defaults. I don't think one should get rid of the latex command entirely, the transformation should rather be `\section{title} -> section: title`, maybe `section` with a different face.

I am not sure if we shouldn't rather pursue the idea of an unflattened `consult-imenu` (it could be toggled via C-u prefix argument). @Hugo-Heagren are you aware of the `embark-export` functionality in normal buffers? If you type `M-x embark-export RET` you get a dynamically updating outline based on `consult-outline`. @oantolin added this recently to Embark. We could also use `consult-imenu` instead, where only the leaves are displayed instead of the path. @oantolin What do you think?

**Comment by oantolin** [comment] 2021-12-16 14:08
> If you type `M-x embark-export RET` you get a dynamically updating outline based on `consult-outline`

Minor correction: if you use `embark-export` the outline does not update dynamically, for that you need to use `embark-collect-live`.

**Comment by oantolin** [comment] 2021-12-16 14:10
Another option would be to have the transformed heading just as a display property. That way you can still match on `\section` but don't have to see the markup.

**Comment by minad** [comment] 2021-12-16 14:27
> Another option would be to have the transformed heading just as a display property. That way you can still match on \section but don't have to see the markup. The exporter would remove that display property, to ensure easy editing, but embark collect could keep it since it isn't editable anyway.

I've considered this, but one should generally avoid the display property for completion candidates since then you won't see the completion style highlighting anymore. From my experience it is better to keep the completion candidate formatting plain and simple, already the disambiguation tofus are quite painful to work with.

If you only want to modify the formatting on the display level it should be implemented at the level of the completion style, e.g., in `vertico--format-candidate`.

**Comment by oantolin** [comment] 2021-12-16 14:58
Wait a second! I think `imenu` already does what @Hugo-Heagren  wants! For LaTeX it does not return _nested_ items, it just _indents_ them according to depth.

**Comment by minad** [comment] 2021-12-16 15:52
Yes, both imenu and consult-imenu already do what @Hugo-Heagren wants. I already edited this in my comment above.

Therefore I currently lean to keeping things as is. consult-outline is for untransformed candidates and consult-imenu/imenu is for high-level TOCs.

**Comment by minad** [comment] 2021-12-21 11:34
@Hugo-Heagren Please let us know what you think about consult-imenu!

Closing.

**Closed by minad** 2021-12-21 11:34 UTC
Labels: enhancement

**Comment by Hugo-Heagren** [comment] 2021-12-22 14:47
> @Hugo-Heagren Please let us know what you think about consult-imenu!

Just tried it and this is exaclty what I was looking for. I need to update my keybindings but that's about it. Thanks!!!
