### ISSUE TITLE
consult-completion-in-region breaks default completion

### ISSUE THREAD

**Issue by tarsius** [minad/consult#350] opened 2021-07-03 09:23 UTC
Nowadays I mostly use `vertico` but recently had to test some completion-related changes in Magit with some other completion frameworks.  After turning of `vertico-mode` completion was completely broken: `TAB` (`minibuffer-complete`) did not complete but enter a recursive minibuffer.

Took me a while to figure out, but eventually I noticed that `minibuffer-complete` uses `completion-in-region`, which I found a bit surprising.  That function directs the work to `completion-in-region-function`, which in my case was `consult-completion-in-region` because I followed the suggestion in the documentation to do that.

Looking at `consult-completion-in-region` I can see that that calls `completing-read`...

How can this infinite (albeit slow, because a human is involved) recursion be broken when using default completion? How is this situation already prevented when using `vertico`?

**Comment by minad** [comment] 2021-07-03 10:09
consult-completion-in-region ist not supposed to be used in combination with default completion, since this is pointless. Default completion already supports completion in region by itself.

consult-completion-in-region is only useful in combination with minibuffer completion UIs like Vertico, Icomplete or Selectrum.

I can give this a check to see what exactly breaks. Overall this is a wontfix.

**Comment by minad** [comment] 2021-07-03 11:23
I tested consult-completion-in-region with the default completion UI. It works as intended, no bugs etc, but of course it is weird. I clarified the README in 7dd627efcbd654ed215cd49ab33b62f900268f82.

**Closed by minad** 2021-07-03 11:23 UTC

**Comment by tarsius** [comment] 2021-07-03 13:03
> I tested consult-completion-in-region with the default completion UI. It works as intended, no bugs etc, but of course it is weird.

"As intended" maybe, but also extremely surprising for the uninitiated.  [The documentation update is a clear improvement, but still.]

I would think that many users who are coming to `vertico` from `ivy` or `selectrum` expect not only "regular minibuffer completion" to stop relying on the `*Completions*` buffer but also `completion-at-point`. At least that is what I expected but when my expectations weren't met, I read the documentation and learned:

> In case you want to use Vertico for completion-at-point/completion-in-region, you can use the function consult-completion-in-region provided by the Consult package.

At the time I thought that that is a bit inconvenient but not worth changing. So I added the suggested setting and moved on.

Months later I changed Magit's wrapper around `completing-read-multiple` and I needed to test that change with various completing frameworks.  In `vertico-mode` it worked.  Then I turned off that mode and minibuffer completion was completely broken -- not just the Magit wrapper, minibuffer completion as such.  Of course I looked at my configuration and commented out a few things that might cause this.  But this setting did not look like it might possibly be related:

``` elisp
(setq completion-in-region-function 'consult-completion-in-region)
```

The breakage wasn't limited to at-point completion but affected all minibuffer completion. Of course now I know that the default minibuffer completion makes use of at-point completion, but this is not something that one just happens to know or even just intuitively assumes.

Now I know that simply turning of `vertico-mode` is not enough to restore default minibuffer & at-point completion.  For that I additionally have to evaluate `(setq completion-in-region-function 'completion--in-region)`.

IMO this is not satisfying, and I fear that in a few months I will have forgotten about it again. I think that I should be able to use vertico for both minibuffer AND at-point completion; AND also be able to turn all of that off using just the `vertico-mode` toggle command.

IMO it would be best if turning ON (and off of course) `vertico-mode` also affected at-point completion, either always or only if some new `vertico-for-at-point-completion` option were non-nil.

Alternatively maybe `consult-completion-in-region` could check if one of the supported modes is enable and if that is not the case, then it could fallback to `ompletion--in-region`.

**Comment by minad** [comment] 2021-07-03 13:52
> Now I know that simply turning of vertico-mode is not enough to restore default minibuffer & at-point completion. For that I additionally have to evaluate (setq completion-in-region-function 'completion--in-region).

Indeed. It may make sense to add an example configuration to the Vertico or the Consult readme, which enables `consult-completion-in-region` only when Vertico is active. However I do not generally recommend to use `consult-completion-in-region`. I recommend Corfu/Company instead.

> IMO it would be best if turning ON (and off of course) vertico-mode also affected at-point completion, either always or only if some new vertico-for-at-point-completion option were non-nil.

I agree that it is not particularly user friendly, but there is no better way if I don't want to couple the packages. The setting depends highly on the preferences of the user. Personally I am not even using `consult-completion-in-region`. Or for example, you may want to use `consult-completion-in-region` for some major modes and Corfu in some other buffers.

Furthermore, users who want to try out or combine different completion systems (like you are doing here) have additional special requirements.  Switching completion systems may involve changing other configuration variables.

Note that `consult-completion-in-region` is a feature which is targeted more for experienced users. Therefore it is not part of the example configuration. Most people prefer to enable Corfu/Company for in-buffer completion instead. There are even more issues with `consult-completion-in-region` - it is not guaranteed that it works under all circumstances, since this transfer from the completion at point to the minibuffer can break assumptions of the completion table. For example lsp-mode is problematic with `consult-completion-in-region`.

**Comment by minad** [comment] 2021-07-03 14:01
I also added the example configuration to the Vertico README in https://github.com/minad/vertico/commit/ea82a4a326434410a9706c49d0c3dcd3efa8130c.

**Comment by tarsius** [comment] 2021-07-03 14:54
For now I am using

```elisp
  (setq completion-in-region-function
        (lambda (start end collection &optional predicate)
          (if vertico-mode
              (consult-completion-in-region start end collection predicate)
            (completion--in-region start end collection predicate))))
```

Because `vertico-mode` is enabled at startup and I might then disable it interactively to quickly try something else.
