### ISSUE TITLE
Problems with tramp, toolbox, and consult-ripgrep

### ISSUE THREAD

**Issue by dm19** [minad/consult#540] opened 2022-03-19 02:37 UTC
Consult-ripgrep is having trouble finding the ripgrep executable while attached to a [Fedora toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/) container. Consult-grep runs inside the container with no issues, but consult-ripgrep gives this error:
`Error running timer: (file-missing "Searching for program" "No such file or directory" "rg")`

`(find-executable "rg" t)` in a buffer opened in the toolbox with tramp gives `/usr/bin/rg` as expected, and I do not have rg installed on the host.

Tested with `emacs -Q` and the following buffer:

```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	    (url-retrieve-synchronously
	     "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	     'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(require 'straight)
(straight-use-package  'consult)
(straight-use-package 'vertico)
(vertico-mode)
(setq completion-styles '(substring))

(require 'tramp)
(push
 (cons
  "toolbox"
  '((tramp-login-program "toolbox")
    (tramp-login-args (("enter" "-c") ("%h")))
    (tramp-remote-shell "/bin/sh")
    (tramp-remote-shell-args ("-i") ("-c"))))
 tramp-methods)
```

Enter toolbox with `find-file /toolbox:fedora-toolbox-35:/path/to/file`

edit: It appears that if I install ripgrep on my host, the function works in the container
```
Tramp: Opening connection  *consult-async-stderr* for fedora-toolbox-35 using toolbox...done
Tramp: Opening connection rg for fedora-toolbox-35 using toolbox...done
```
But I would expect the function to run in the container if rg is available there whether or not it is available on the host? Is that incorrect?

**Comment by minad** [comment] 2022-03-19 10:00
The problem is that we check the locally installed ripgrep program first for the supported regexp type and then cache the result globally.

https://github.com/minad/consult/blob/800824601b610016066991d6e2dde198d4b0ad8f/consult.el#L4467-L4472

We could cache the regexp type per directory only or per host, but this seems like an ugly complication to me. I consider this a minor issue. Better ensure that your host and server are at least somewhat consistent. Alternatively just preset the variables to a values which works for you:

~~~ elisp
(setq consult--find-regexp-type 'basic
      consult--grep-regexp-type 'pcre
      consult--ripgrep-regexp-type 'extended)
~~~

I close this as wontfix. But if you like, feel free to investigate possible solutions and we can reconsider.

**Closed by minad** 2022-03-19 10:00 UTC

**Comment by dm19** [comment] 2022-03-19 15:45
> Better ensure that your host and server are at least somewhat consistent.

I won't pretend to really know what I'm talking about, but I think the idea behind the container based development workflow driving things like Fedora Silverblue is to have a small stable base with most of the tooling kept in the containers rather than on the host.

> ```
> (setq consult--find-regexp-type 'basic
>       consult--grep-regexp-type 'pcre
>       consult--ripgrep-regexp-type 'extended)
> ```

Works. Good enough for me.
