### ISSUE TITLE
Conflict with Modus theme

### ISSUE THREAD

**Issue by astoff** [minad/consult#764] opened 2023-03-08 12:34 UTC
With Modus, in the preview buffers, the fake cursor covers the letters:

![Screenshot from 2023-03-05 11-06-11](https://user-images.githubusercontent.com/6500902/223713972-8cfe1fcf-2dfb-48cc-9a29-f8e717283836.png)

This can be solved by nullifying the `consult-preview-cursor` face:

![Screenshot from 2023-03-08 13-32-27](https://user-images.githubusercontent.com/6500902/223714338-6a788be3-ad82-4e71-aa72-b3c67102db51.png)

Which makes me wonder, why is a fake cursor at all necessary? The selected window is the minibuffer so obviously the cursor can only be there.

cc @protesilaos

**Comment by minad** [comment] 2023-03-08 15:16
This should be fixed in Modus. I still use Modus 3 and there is no problem there, so this is a regression.

**Closed by minad** 2023-03-08 15:16 UTC

**Comment by astoff** [comment] 2023-03-18 11:03
Maybe _this_ is a good reason to get rid of the fake cursor? It's a TAB character.

![Screenshot from 2023-03-18 12-01-17](https://user-images.githubusercontent.com/6500902/226101448-e6acbbf4-b932-4542-ae70-dc48efea3099.png)

**Comment by astoff** [comment] 2023-03-18 11:33
I set `consult-preview-cursor` (it _is_ called a cursor...) to the empty face and I still know exactly where I will jump:

![image](https://user-images.githubusercontent.com/6500902/226102955-bf963f01-a516-40e2-8b88-4407469ff332.png)

I guess Prot is aware, since we tagged him.

**Comment by minad** [comment] 2023-03-18 11:36
> I set consult-preview-cursor (it is called a cursor...) to the empty face and I still know exactly where I will jump:

I don't see this. When I execute `(face-spec-reset-face 'consult-preview-cursor)` I don't see the place anymore, where I am going to jump. If anything needs to be done about this issue, it must be done in Modus.

**Comment by astoff** [comment] 2023-03-18 11:41
You probably customized `cursor-in-non-selected-windows`, in which case you're getting exactly what you have asked for :-).

**Comment by minad** [comment] 2023-03-18 11:45
> You probably customized cursor-in-non-selected-windows, in which case you're getting exactly what you have asked for :-).

You are right about this. As an alternative I could get rid of the cursor overlay and instead enforce that `cursor-in-non-selected-windows` is non-nil. But then, the candidate strings are also fontified with the `consult-preview-cursor` face, so I rather keep it as is.

**Comment by protesilaos** [comment] 2023-03-20 12:27
Hello folks!  I am slow to respond due to some tricky circumstances.

I did push an update for this in commit `7f2952c` on 2023-03-08.  Please let me know if the issue persists.  It seems okay on my end.

**Comment by minad** [comment] 2023-04-16 01:16
@astoff @protesilaos I finally came to the conclusion that creating a fake cursor overlay is maybe not the best idea. I still override `cursor-in-non-selected-windows`. Please test!

**Comment by minad** [comment] 2023-05-07 16:53
I've now removed the `consult-preview-cursor` face and introduce a `consult-highlight-mark` face instead, which is not used for preview, only for completion candidates. See https://github.com/minad/consult/commit/267b0c9d86e7f593d042a1669a03782ecac82a54. @protesilaos Please remove the faces `consult-preview-cursor` from Modus and Ef and adapt `consult-highlight-mark` appropriately if you think the defaults can be improved.

**Comment by protesilaos** [comment] 2023-05-08 07:20
Thank you @minad!  I am working on it now.

Conceptually, it is correct for `consult-highlight-mark` to ultimately inherit `match`, though it may be hard to spot in the minibuffer because it is one character long.  I don't think this is a problem per se, but I am pointing it out.

Assuming, we need something a bit more intense, we can try `secondary-selection`.  At the theme level, this could be an even more intense colour, though I don't want to make this over-the-top, as the preview facility does a better job at showing the context.

**Comment by minad** [comment] 2023-05-09 06:59
> Thank you @minad! I am working on it now.

Thanks, I've seen you removed the faces.

> Conceptually, it is correct for consult-highlight-mark to ultimately inherit match, though it may be hard to spot in the minibuffer because it is one character long. I don't think this is a problem per se, but I am pointing it out.

You are right. Thanks for pointing it out. I also don't consider it a problem given that the exact marker position in the completion candidate is not that important.

> Assuming, we need something a bit more intense, we can try secondary-selection. At the theme level, this could be an even more intense colour, though I don't want to make this over-the-top, as the preview facility does a better job at showing the context.

I am not sure about secondary-selection. In Modus the face of match and secondary-selection is the same. In the default "theme", secondary-selection is even less intense.

For now I would leave things as is. The problem pointed out by @astoff has been resolved and the confusing cursor preview face is gone. The consult-highlight-mark face is not as widely used and not that important in Consult.
