### ISSUE TITLE
consult-yank-pop: wrong-number-of-arguments #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_38> 3

### ISSUE THREAD

**Issue by terlar** [minad/consult#82] opened 2020-12-21 14:49 UTC
When issuing the command `consult-yank-pop` I can select the entries from the list, but as soon as I select one of the entries to insert I get a an error regarding `wrong-number-of-arguments`.

```
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_38> 3)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_38>("" (#("\"M-y\" 'counsel-yank-pop" 0 5 (composition nil face (font-lock-string-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 5 6 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 6 7 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 7 23 (composition nil face (highlight-quoted-symbol org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t)) #("\"M-y\"" 0 5 (composition nil face (font-lock-string-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t)) #("'" 0 1 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t ws-butler-chg chg fontified t)) #("ivy-yasnippet" 0 3 (fontified t ws-butler-chg chg font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil) 3 4 (fontified t ws-butler-chg delete font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil) 4 13 (fontified t ws-butler-chg chg font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil)) #("  :general\n  ([remap yas-insert-..." 0 2 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 2 10 (composition nil face (font-lock-builtin-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 10 13 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 13 14 (composition nil face (rainbow-delimiters-depth-2-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 14 15 (composition nil face (rainbow-delimiters-depth-3-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 15 39 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 39 40 (composition nil face (rainbow-delimiters-depth-3-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 40 41 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 41 42 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 42 55 (composition nil face (highlight-quoted-symbol org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) ...) #("*** smart-jump\nSome modes actual..." 0 4 (face org-variable-pitch-fixed-face prettify-symbols-end 67875 prettify-symbols-start 67871 composition (4 4 ...) fontified t) 4 15 (face org-level-3 fontified t) 15 83 (fontified t) 83 84 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 84 94 (org-emphasis t font-lock-multiline t face (org-code) fontified t) 94 95 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 95 176 (fontified t) 176 177 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 177 186 (org-emphasis t font-lock-multiline t face (org-code) fontified t) 186 187 (invisible org-link org-emphasis t font-lock-multiline t fontified t) ...) #("[[https://github.com/jojojames/s..." 0 42 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link invisible org-link htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 42 43 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link invisible org-link rear-nonsticky (mouse-face highlight keymap invisible intangible help-echo org-linked-text htmlize-link) htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 43 52 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 52 53 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link rear-nonsticky (mouse-face highlight keymap invisible intangible help-echo org-linked-text htmlize-link) htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t)) "https://drym.org/on-attribution/") "\"M-y\" 'counsel-yank-pop")
  #f(compiled-function (cmd cand state) #<bytecode 0x34c2453bdf8947e>)(restore "\"M-y\" 'counsel-yank-pop" nil)
  #f(compiled-function () #<bytecode 0x9fe8c047a9ecd72>)()
  consult--preview-install(#f(compiled-function (cmd cand state) #<bytecode 0x34c2453bdf8947e>) #f(compiled-function () #<bytecode 0x19a52cfdb9c4ec96>))
  #<subr consult--read>("Yank text: " (#("\"M-y\" 'counsel-yank-pop" 0 5 (composition nil face (font-lock-string-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 5 6 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 6 7 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 7 23 (composition nil face (highlight-quoted-symbol org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t)) #("\"M-y\"" 0 5 (composition nil face (font-lock-string-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t)) #("'" 0 1 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t ws-butler-chg chg fontified t)) #("ivy-yasnippet" 0 3 (fontified t ws-butler-chg chg font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil) 3 4 (fontified t ws-butler-chg delete font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil) 4 13 (fontified t ws-butler-chg chg font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil)) #("  :general\n  ([remap yas-insert-..." 0 2 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 2 10 (composition nil face (font-lock-builtin-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 10 13 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 13 14 (composition nil face (rainbow-delimiters-depth-2-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 14 15 (composition nil face (rainbow-delimiters-depth-3-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 15 39 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 39 40 (composition nil face (rainbow-delimiters-depth-3-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 40 41 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 41 42 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 42 55 (composition nil face (highlight-quoted-symbol org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) ...) #("*** smart-jump\nSome modes actual..." 0 4 (face org-variable-pitch-fixed-face prettify-symbols-end 67875 prettify-symbols-start 67871 composition (4 4 ...) fontified t) 4 15 (face org-level-3 fontified t) 15 83 (fontified t) 83 84 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 84 94 (org-emphasis t font-lock-multiline t face (org-code) fontified t) 94 95 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 95 176 (fontified t) 176 177 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 177 186 (org-emphasis t font-lock-multiline t face (org-code) fontified t) 186 187 (invisible org-link org-emphasis t font-lock-multiline t fontified t) ...) #("[[https://github.com/jojojames/s..." 0 42 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link invisible org-link htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 42 43 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link invisible org-link rear-nonsticky (mouse-face highlight keymap invisible intangible help-echo org-linked-text htmlize-link) htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 43 52 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 52 53 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link rear-nonsticky (mouse-face highlight keymap invisible intangible help-echo org-linked-text htmlize-link) htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t)) "https://drym.org/on-attribution/") :history t :sort nil :category kill-ring :require-match t :preview #f(compiled-function (cmd cand state) #<bytecode 0x1a1c7f4fe924b4e3>))
  apply(#<subr consult--read> ("Yank text: " (#("\"M-y\" 'counsel-yank-pop" 0 5 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 5 6 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 6 7 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 7 23 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t)) #("\"M-y\"" 0 5 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t)) #("'" 0 1 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t ws-butler-chg chg fontified t)) #("ivy-yasnippet" 0 3 (fontified t ws-butler-chg chg font-lock-fontified t help-echo nil src-block t font-lock-multiline t face ... composition nil) 3 4 (fontified t ws-butler-chg delete font-lock-fontified t help-echo nil src-block t font-lock-multiline t face ... composition nil) 4 13 (fontified t ws-butler-chg chg font-lock-fontified t help-echo nil src-block t font-lock-multiline t face ... composition nil)) #("  :general\n  ([remap yas-insert-..." 0 2 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 2 10 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 10 13 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 13 14 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 14 15 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 15 39 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 39 40 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 40 41 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 41 42 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 42 55 (composition nil face ... font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) ...) #("*** smart-jump\nSome modes actual..." 0 4 (face org-variable-pitch-fixed-face prettify-symbols-end 67875 prettify-symbols-start 67871 composition ... fontified t) 4 15 (face org-level-3 fontified t) 15 83 (fontified t) 83 84 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 84 94 (org-emphasis t font-lock-multiline t face ... fontified t) 94 95 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 95 176 (fontified t) 176 177 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 177 186 (org-emphasis t font-lock-multiline t face ... fontified t) 186 187 (invisible org-link org-emphasis t font-lock-multiline t fontified t) ...) #("[[https://github.com/jojojames/s..." 0 42 (font-lock-multiline t keymap ... mouse-face highlight face org-link invisible org-link htmlize-link ... help-echo "LINK: https://github.com/jojojam..." fontified t) 42 43 (font-lock-multiline t keymap ... mouse-face highlight face org-link invisible org-link rear-nonsticky ... htmlize-link ... help-echo "LINK: https://github.com/jojojam..." fontified t) 43 52 (font-lock-multiline t keymap ... mouse-face highlight face org-link htmlize-link ... help-echo "LINK: https://github.com/jojojam..." fontified t) 52 53 (font-lock-multiline t keymap ... mouse-face highlight face org-link rear-nonsticky ... htmlize-link ... help-echo "LINK: https://github.com/jojojam..." fontified t)) "https://drym.org/on-attribution/") :history t :sort nil :category kill-ring :require-match t :preview #f(compiled-function (cmd cand state) #<bytecode 0x1a1c7f4fe924b4e3>)))
  consult--read("Yank text: " (#("\"M-y\" 'counsel-yank-pop" 0 5 (composition nil face (font-lock-string-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 5 6 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 6 7 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 7 23 (composition nil face (highlight-quoted-symbol org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t)) #("\"M-y\"" 0 5 (composition nil face (font-lock-string-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t)) #("'" 0 1 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t ws-butler-chg chg fontified t)) #("ivy-yasnippet" 0 3 (fontified t ws-butler-chg chg font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil) 3 4 (fontified t ws-butler-chg delete font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil) 4 13 (fontified t ws-butler-chg chg font-lock-fontified t help-echo nil src-block t font-lock-multiline t face (highlight-quoted-symbol org-block) composition nil)) #("  :general\n  ([remap yas-insert-..." 0 2 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 2 10 (composition nil face (font-lock-builtin-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 10 13 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 13 14 (composition nil face (rainbow-delimiters-depth-2-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 14 15 (composition nil face (rainbow-delimiters-depth-3-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 15 39 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 39 40 (composition nil face (rainbow-delimiters-depth-3-face org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 40 41 (composition nil face (org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 41 42 (composition nil face (highlight-quoted-quote org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) 42 55 (composition nil face (highlight-quoted-symbol org-block) font-lock-multiline t src-block t help-echo nil font-lock-fontified t fontified t) ...) #("*** smart-jump\nSome modes actual..." 0 4 (face org-variable-pitch-fixed-face prettify-symbols-end 67875 prettify-symbols-start 67871 composition (4 4 ...) fontified t) 4 15 (face org-level-3 fontified t) 15 83 (fontified t) 83 84 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 84 94 (org-emphasis t font-lock-multiline t face (org-code) fontified t) 94 95 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 95 176 (fontified t) 176 177 (invisible org-link org-emphasis t font-lock-multiline t fontified t) 177 186 (org-emphasis t font-lock-multiline t face (org-code) fontified t) 186 187 (invisible org-link org-emphasis t font-lock-multiline t fontified t) ...) #("[[https://github.com/jojojames/s..." 0 42 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link invisible org-link htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 42 43 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link invisible org-link rear-nonsticky (mouse-face highlight keymap invisible intangible help-echo org-linked-text htmlize-link) htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 43 52 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t) 52 53 (font-lock-multiline t keymap (keymap ... ... ...) mouse-face highlight face org-link rear-nonsticky (mouse-face highlight keymap invisible intangible help-echo org-linked-text htmlize-link) htmlize-link (:uri "https://github.com/jojojames/sma...") help-echo "LINK: https://github.com/jojojam..." fontified t)) "https://drym.org/on-attribution/") :history t :sort nil :category kill-ring :require-match t :preview #f(compiled-function (cmd cand state) #<bytecode 0x1a1c7f4fe924b4e3>))
  consult--yank-read()
  consult-yank()
  consult-yank-pop(1)
```

I am running `GNU Emacs 28.0.50`, more specifically a commit from emacs-pgtk-nativecomp (https://github.com/flatwhatson/emacs/commit/11c956050b57c4a2e8b9a8186b22761ed752dc20).

**Comment by minad** [comment] 2020-12-21 14:55
duplicate of #80

**Closed by minad** 2020-12-21 14:55 UTC

**Comment by terlar** [comment] 2020-12-21 14:57
Thank you, I just updated my packages this morning, but I see it was fixed 3 hours ago. Will try to update, thank you for the quick resolution.

**Comment by DivineDominion** [comment] 2020-12-23 08:29
👏  looked for this, too, and found out that a fix is already out. Great work!

**Comment by minad** [comment] 2020-12-23 08:45
Thanks! But having such a bug is not so great actually ;) I should setup some testing to catch basic bugs like these. Let's see what Selectrum is doing regarding tests https://github.com/raxod502/selectrum/issues/299...
