### ISSUE TITLE
Face issue with native compilation on Emacs 28

### ISSUE THREAD

**Issue by tumashu** [minad/consult#274] opened 2021-04-13 03:07 UTC
![截图_2021-04-13_10-43-53](https://user-images.githubusercontent.com/67725/114490990-66ba5d00-9c48-11eb-9f89-8042aef29544.png)

**Comment by tumashu** [comment] 2021-04-13 03:08
The  *blue* looks ugly, how to config it ?

**Comment by minad** [comment] 2021-04-13 03:45
This is a theme issue. I don't know which face affect this, ~minibuffer-prompt~ or ~completion-annotation~. Please try another theme. For example I can highly recommend the Modus themes. modus-vivendi looks pretty similar what you have here and supports *every package*.

**Comment by tumashu** [comment] 2021-04-13 04:10
I use modus

**Comment by minad** [comment] 2021-04-13 04:12
I don't have the issue with modus-operandi/modus-vivendi. Please try with emacs -Q only loading Vertico and Modus.

**Comment by tumashu** [comment] 2021-04-13 04:33
![截图_2021-04-13_12-31-14](https://user-images.githubusercontent.com/67725/114497340-78a1fd00-9c54-11eb-81ad-ac66dd63a636.png)

emacs -Q have problem too,  emacs 28's problem?

**Comment by tumashu** [comment] 2021-04-13 04:34
![截图_2021-04-13_12-31-14](https://user-images.githubusercontent.com/67725/114497376-90798100-9c54-11eb-8888-6c69e0fe3412.png)

**Comment by tumashu** [comment] 2021-04-13 04:40
![Uploading 截图_2021-04-13_12-33-07.png…]()

**Comment by oantolin** [comment] 2021-04-13 04:44
Debugging this type of problem is one of the many advantages of showing completions in a regular buffer rather that a minibuffer. 😛 Fortunately you can configure Selectrum to do so as follows:

```elisp
(setq selectrum-display-action '(display-buffer-in-side-window (side . bottom) (slot . -1)))
```

Then you can put point on the incorrectly colored character and use `C-u C-x =` to see what face they are in.

**Comment by minad** [comment] 2021-04-13 05:01
Always the buffer propaganda. Fortunately we can do this:

~~~ elisp
(defun vertico--bufferize (candidates)
  (let ((buffer (get-buffer-create "*Vertico*")))
    (with-current-buffer buffer
      (erase-buffer)
      (insert (string-join candidates)))
    (display-buffer buffer)))

(advice-add #'vertico--display-candidates :after #'vertico--bufferize)
~~~

I think the main issue I am having with candidates in buffers is that the prompt is not near to the currently selected candidate. With the minibuffer popping up like this I always have the prompt and the current candidate close to each other and this gives me a perceived speed up.

**Comment by minad** [comment] 2021-04-13 05:04
@tumashu If you see it on emacs -Q and only modus+vertico and only on 28 and nowhere else it sounds like a bug. Do you use a recent Emacs 28 or some older version? You may also ask @protesilaos if he has seen such an issue before. He is using a recent Emacs 28 as far as I know.

**Comment by oantolin** [comment] 2021-04-13 05:10
@minad, in case you haven't noticed @tumushu's config in the screenshot loads selectrum, not vertico.

**Comment by tumashu** [comment] 2021-04-13 05:11
I think it should come from:

```
         (consult--multi-align (propertize
                                " " 'display
                                `(space :align-to (+ left ,(cadr candidates)))))

```

**Comment by tumashu** [comment] 2021-04-13 05:16
emacs27 have no this problem.

**Comment by minad** [comment] 2021-04-13 05:17
@oantolin Right, I got confused since @tumashu also opened a Vertico issue recently.

@tumashu So this is an Emacs 28 issue. You may want to report it upstream. Maybe @protesilaos can help. I suspect he would have noticed such a serious problem by now.

**Comment by tumashu** [comment] 2021-04-13 05:32
emacs27 have no this problem.

**Comment by protesilaos** [comment] 2021-04-13 05:50
Hello @tumashu!  Can you please give me the package configs that you are using?  [This screenshot here](https://github.com/minad/consult/issues/274#issuecomment-818429445) makes me think that the problem may not be with the Modus themes, though I wish to investigate it.

**Comment by tumashu** [comment] 2021-04-13 05:57
```
         (consult--multi-align (propertize
                                "  " 'display
                                `(space :align-to (+ left ,(cadr candidates)))))

```

when I  add 2 space in this code, the problem dispear, I do not why

**Comment by protesilaos** [comment] 2021-04-13 05:58
This is what I get with `M-x consult-buffer` and simply enabling `selectrum-mode`:

![Screenshot from 2021-04-13 08-56-45](https://user-images.githubusercontent.com/12828033/114503658-54372800-9c36-11eb-904f-c5623e42ec26.png)
![Screenshot from 2021-04-13 08-56-48](https://user-images.githubusercontent.com/12828033/114503661-55685500-9c36-11eb-95ef-656296ed67e7.png)

**Comment by protesilaos** [comment] 2021-04-13 06:05
@oantolin How do you move the point in this buffer?  I can't seem to move freely and the line remains fixed.  It only responds to movements from the minibuffer---a remote control of sorts.

```elisp
(setq selectrum-display-action '(display-buffer-in-side-window (side . bottom) (slot . -1)))
```

Though I still cannot reproduce the issue.

**Comment by tumashu** [comment] 2021-04-13 06:08
This code seem to fix the problem
```
         (consult--multi-align (propertize
                                (substring-no-properties " ")
                                'display
                                `(space :align-to (+ left ,(cadr candidates)))))

```

**Comment by protesilaos** [comment] 2021-04-13 06:18
It seems that the face which gives you the blue with the Modus themes is `consult-preview-match`.  While the yellow in your screenshot that I linked to earlier comes from the `match` face.

**Comment by oantolin** [comment] 2021-04-13 06:23
> @oantolin How do you move the point in this buffer? I can't seem to move freely and the line remains fixed. It only responds to movements from the minibuffer---a remote control of sorts.

I should have added that you can close the minibuffer and explore the buffer afterwards, @protesilaos.

**Comment by minad** [comment] 2021-04-13 07:00
@tumashu The potential fixes you are pasting here are suspicious. Are you using the newest version of Emacs 28?

~~~ elisp
         (consult--multi-align (propertize
                                (substring-no-properties " ")
                                'display
                                `(space :align-to (+ left ,(cadr candidates)))))

         (consult--multi-align (propertize
                                "  " 'display
                                `(space :align-to (+ left ,(cadr candidates)))))
~~~

It seems that the string is somehow modified. In `consult--multi-annotate` that string is copied, so the issue should not happen.
 
~~~ elisp
(and ann (concat consult--multi-align ann))))
~~~

**Comment by tumashu** [comment] 2021-04-13 08:29
I use emacs28  gccemacs 20210330, maybe I should test in emacs28 master

**Comment by hmelman** [comment] 2021-04-13 13:18
FWIW, I've seen discussions in emacs mailing lists about a change in Emacs 28 involving the :extend face attribute that cause similar looking issues.  E.g., [Emacs bug #37774](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37774)

**Comment by tumashu** [comment] 2021-04-14 00:22
maybe it is issue with native-compilation

**Comment by minad** [comment] 2021-04-14 11:40
@hmelman This issue is not related.

**Comment by junyi-hou** [comment] 2021-04-15 05:40
I have the same issue with `emacs -Q -l debug-init.el`. I am on `emacs-native-comp-pgtk` branch @ 04/14/2021. The content of `debug-init.el` is
```
;; -*- lexical-binding: t; -*-

;; ============================
;; initializing package manager
;; ============================

(setq straight-repository-branch "develop"
      straight-use-package-by-default t
      straight-vc-git-default-protocol 'https)

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

;; ======================================================
;; test code below
;; run with `emacs -q -l debug-init.el'
;; ======================================================

(use-package selectrum)
(selectrum-mode 1)

(use-package consult)
```

**Comment by jakanakaevangeli** [comment] 2021-04-20 21:16
I tracked this down to `#(" " props...)` being collapsed with `" "` in
native-compiled files. Reported as bug#47922.

**Comment by minad** [comment] 2021-04-20 21:23
@jakanakaevangeli Thank you. This goes in the direction I had expected - some invalid optimization? @AndreaCorallo is currently investigating https://github.com/minad/vertico/issues/15/https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47868. You may want to link to that bug report in your bug report. It is likely that those too are related, since both are about face issues.

**Comment by jakanakaevangeli** [comment] 2021-04-20 22:08
Yup, they are related, because when I tried replacing all occurrences of
#("str" 0 3 props...) with (propertize "str" props...) in vertico.el the
vertico prompt issues were gone.
I'll link the bug reports on debbugs.

**Comment by minad** [comment] 2021-04-20 22:09
Haha, I guess I am the only one who uses propertized literals :D

**Comment by minad** [comment] 2021-04-21 13:34
Closing here, bug is being worked on https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47868

**Closed by minad** 2021-04-21 13:34 UTC
Labels: upstream bug
