### ISSUE TITLE
consult-buffer looks wired

### ISSUE THREAD

**Issue by 404cn** [minad/consult#305] opened 2021-05-11 09:34 UTC
![consult-buffer](https://user-images.githubusercontent.com/24653356/117793570-ec98ea80-b27e-11eb-9915-ff948ecae0c2.png)

How can I make it looks normal?

**Comment by minad** [comment] 2021-05-11 10:10
You are using an outdated version of Emacs 28 with native compilation. Update to the newest Emacs master to fix the issue. Duplicate of #274.

**Closed by minad** 2021-05-11 10:10 UTC
