### ISSUE TITLE
consult buffer preview loses focus in exwm after previewing X windows

### ISSUE THREAD

**Issue by codygman** [minad/consult#239] opened 2021-03-01 17:20 UTC
It's probably the case that the exwm managed X window steals focus actually. 

The syntax might be wrong, but I think a workaround would be:

```
(advice-add 'exwm-reset :after 'consult-buffer-preview)
```

Except you'd want to only call exwm-reset for X buffers and not normal emacs buffers. This is imperfect, but hitting my hotkey for exwm-reset is how I get my focus out of the x window back into the buffer switch minibuffer.

**Comment by minad** [comment] 2021-03-01 18:18
Duplicate of #178 and #204. Please also take a look at https://github.com/minad/consult/wiki#do-not-preview-exwm-windows-or-tramp-buffers. Maybe you want to add your workaround to the wiki too, such that `exwm-reset` is called for X buffers. Maybe @thomasheartman would be interested in this too and could be of help?

Besides that I cannot do anything on the side of Consult. I think the issue should actually be fixed by EXWM (https://github.com/ch11ng/exwm/issues/813). Note that I am not an EXWM user myself and I cannot give full support when EXWM is combined with Consult.

**Closed by minad** 2021-03-01 18:18 UTC

**Comment by codygman** [comment] 2021-03-01 18:39
> Duplicate of #178 and #204. Please also take a look at https://github.com/minad/consult/wiki#do-not-preview-exwm-windows-or-tramp-buffers. Maybe you want to add your workaround to the wiki too, such that `exwm-reset` is called for X buffers. Maybe @thomasheartman would be interested in this too and could be of help?
> 
> Besides that I cannot do anything on the side of Consult. I think the issue should actually be fixed by EXWM ([ch11ng/exwm#813](https://github.com/ch11ng/exwm/issues/813)). Note that I am not an EXWM user myself and I cannot give full support when EXWM is combined with Consult.

Totally understandable you can't support both. 

My fault for not:

1) looking for existing issues and 
2) not consulting the wiki. 

It's kind of rare to have such a great wiki though... good job there!

Thanks for pointing me in the right direction.

**Comment by minad** [comment] 2021-03-01 18:49
No worries, it is okay to open such issues. I only don't want to rediscuss the issue again, since there has already been a very long discussion in #178 and #204. The solution we currently have is not perfect, but a step in the right direction. As soon as we get more information from the EXWM maintainers we can adjust accordingly. I still consider EXWM a fringe setup. On my system I would have great difficulties installing it since I am using i3 on qubes, which is a sandboxed, virtualized environment. I probably would also be unhappy with Emacs hanging from time to time. But I certainly like the idea!

**Comment by thomasheartman** [comment] 2021-03-02 10:01
@minad Thanks for summoning me! This is indeed relevant to my interests.

@codygman That's very interesting about calling `exwm-reset` to fix the focus issues. When using the regular preview functionality now I realized that the X windows don't seem to steal the focus until after they've been de-selected. That is:
1. Preview some other buffer. Works as expected.
2. Preview the X buffer. Focus is still in the minibuffer.
3. Either move to next item or change search term, so that the X buffer is no longer previewed. Focus leaves the minibuffer and ends up in the currently previewed buffer.

Can you confirm whether this is what you're seeing as well?

**Comment by codygman** [comment] 2021-03-02 13:20
@thomasheartman After updating my flake inputs to the latest version of nixpkgs I observed even X windows previewed correctly on my laptop. I'll be updating another machine to that version today and I'll see if that's still the case.

**Comment by codygman** [comment] 2021-03-09 23:30
> @thomasheartman After updating my flake inputs to the latest version of nixpkgs I observed even X windows previewed correctly on my laptop. I'll be updating another machine to that version today and I'll see if that's still the case.

Except microsoft teams apparently :/

**Comment by thomasheartman** [comment] 2021-03-10 07:34
Huh, that's interesting. I haven't gotten around to looking into flakes yet: how does that differ from a regular Nix config? Any reason why windows should act differently? I've disabled previews now because even with the workaround I ran into some issues (think it was with Tramp this time), so I'm not entirely sure how things work these days.

Also, why do you think Teams would act differently to everything else?

**Comment by codygman** [comment] 2021-04-16 15:48
@thomasheartman I ended up disabling previews too because the issue returned at some point.
