### ISSUE TITLE
How to ungroup results? (incl. small documentation bug report)

### ISSUE THREAD

**Issue by dalanicolai** [minad/consult#432] opened 2021-10-04 09:13 UTC
Probably this is documented somewhere, but I am unable to find it.
When using `consult-ripgrep`, I usually prefer to have a quick overview of the files that contain matches. Because the results are grouped, I can not quickly see all (or multiple) files that contain matches.

I did read about some narrow key, which here, using the Spacemacs `compleseus` layer, is shown to be `<`, but pressing it has no effect (just inserts it in the search field; I am not sure how it is supposed to work).

Finally, a small documentation bug report:
I did also find that it is possible to disable the group titles in the section https://github.com/minad/consult#narrowing-and-grouping, but it looks like you forgot to mention the value that should be passed to the `:group` keyword.

**Comment by dalanicolai** [comment] 2021-10-04 09:15
Of course, I realize now that probably I have to read the vertico documentation for this. But then the small bug report here is still relevant...

**Comment by minad** [comment] 2021-10-04 09:16
I am not sure I understand you. If you disable group titles, the matches are "ungrouped". Or do you mean something else with "ungrouping"?

> but it looks like you forgot to mention the value that should be passed to the :group keyword.

It is nil of course :)

**Comment by minad** [comment] 2021-10-04 09:17
~~~ elisp
(consult-customize consult-ripgrep :group nil)
~~~

You can also disable grouping globally by setting `vertico-group-format` or `selectrum-group-format` to nil. See the respective docstrings.

**Comment by minad** [comment] 2021-10-04 09:19
Fixed in https://github.com/minad/consult/commit/e40ff0466ac301c10be23eccea0c3f7320ec05bc

**Comment by dalanicolai** [comment] 2021-10-04 09:24
I have tried to set it the `:group` to `nil` already, but it had no effect.

By ungrouping I mean to get the filename on each line, with the`snippet` with the matched text, behind it (like marginalia). This is what I am used to with Ivy. But that usually certainly is handier for me, because I quickly can see all matched files. And the grouping makes it `cumbersome` to find/see all files contained in the results.

**Comment by minad** [comment] 2021-10-04 09:26
> I have tried to set it the :group to nil already, but it had no effect.

This cannot be. The following works for me and disables grouping only for consult-ripgrep. Note that you have to use the name of the command, e.g., if you wrap `consult-ripgrep` with `my-own-project-search`, you have to customize `my-own-project-search`.

~~~ elisp
(consult-customize consult-ripgrep :group nil
                               my-own-project-search :group nil)
~~~

> By ungrouping I mean to get the filename on each line, with thesnippet with the matched text, behind it (like marginalia). This is what I am used to with Ivy. But that usually certainly is handier for me, because I quickly can see all matched files. And the grouping makes it cumbersome to find/see all files contained in the results.

This will happen if you disable grouping.

**Closed by minad** 2021-10-04 09:26 UTC

**Comment by dalanicolai** [comment] 2021-10-04 09:30
Okay, thanks. I had added some comment, in the meantime, already to my previous comment, but I will try to find out then how to achieve it in Spacemacs. At least I know I am on the right path then.
Thanks for your help, and of course for your work and the really great package!

**Comment by dalanicolai** [comment] 2021-10-04 09:31
Haha, I see you have edited the comment already for how to achieve it in Spacemacs... thanks!

**Comment by minad** [comment] 2021-10-04 09:33
Yes, I edited my comment in the meantime. I assumed that the issue in your case was your custom wrapper. Generally please try to reproduce the issue in a plain emacs -Q instance first before reporting it. Of course I am very much willing to help out with Spacemacs-specific issues (as I did for Doom Emacs). But going first with emacs -Q this will smoothen the process quite a bit. It does not require much effort to spin up consult+vertico in emacs -Q as I documented in https://github.com/minad/consult/#bug-reports.
