### ISSUE TITLE
Incompatibility between Consult preview and `vertico-multiform` in `buffer` display mode

### ISSUE THREAD

**Issue by gcv** [minad/consult#552] opened 2022-04-17 12:35 UTC
Not sure if this should be reported here in the Consult repository or Vertico.

With Vertico configured to display `consult-grep` in dedicated buffer mode, Consult preview using `consult-ripgrep` does not display the search buffer, only the preview buffer.

```elisp
(setq vertico-multiform-categories '((consult-grep buffer)))
```

Running `consult-ripgrep` looks like it does nothing, but typing does a search in an off-screen buffer, and the current window shows preview results.

Setting `consult-preview-key` to `nil` fixes the problem, and shows `consult-ripgrep` in a dedicated buffer, as expected (though obviously it turns off previews globally).

**Comment by minad** [comment] 2022-04-17 13:35
`vertico-buffer` should work with `consult-ripgrep` since this is a configuration which I use myself. However the setup depends on your settings of `display-buffer-alist`, `vertico-buffer-display-action` and `switch-to-buffer-obey-display-actions`. Also there was a bug in Vertico which could lead to the effect you observed. This bug is fixed in Vertico 0.22 (see https://github.com/minad/vertico/commit/7ec0f0c0769496edf4c8376950c2fdeb44b98102). Please try to reproduce the issue with emacs -Q and provide a minimal configuration, seehttps://github.com/minad/consult#bug-reports.

**Closed by minad** 2022-04-17 13:35 UTC

**Comment by gcv** [comment] 2022-04-17 13:54
Got it, thanks. I have Vertico 0.22 installed. The problem was indeed caused by `vertico-buffer-display-action`, which I have set to `'(display-buffer-same-window)`. Is there a way to selectively disable preview for `consult-ripgrep`?

**Comment by minad** [comment] 2022-04-17 13:55
> Is there a way to selectively disable preview for consult-ripgrep?

Yes, it is documented in the Consult README.

**Comment by gcv** [comment] 2022-04-17 14:02
Got it. Thank you very much!

**Comment by minad** [comment] 2022-04-17 14:07
Btw, the exact problem you observed here is documented in the Vertico README in https://github.com/minad/vertico#configure-vertico-per-command-or-completion-category. There is even the following example given. :smile: 

~~~ elisp
;; Configure the buffer display and the buffer display action
(setq vertico-multiform-categories
      '((consult-grep
         buffer
         (vertico-buffer-display-action . (display-buffer-same-window)))))

;; Disable preview for consult-grep commands
(consult-customize consult-ripgrep consult-git-grep consult-grep :preview-key nil)
~~~

**Comment by gcv** [comment] 2022-04-17 14:14
Oh wow. Well, I deserved that. Reading manuals has never been one of my virtues. 🤣

**Comment by minad** [comment] 2022-04-17 14:17
Haha, I didn't recall myself that I had documented this. I don't claim that my manuals are particularly nice to read or well written, but I try at least to document all kinds of special behaviors and edge cases I stumble over.
